import Sidebar from "@/components/Sidebar";
import "../globals.css";
import { Inter, Poppins } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Perpustakaan Sekola",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable}, ${poppins.variable}`}>
        <div className="flex">
          <Sidebar>{children}</Sidebar>
        </div>
      </body>
    </html>
  );
}
